#smtp_server: smtp.qq.com
smtp_server: mail.xx.com
#port: 465
port: 25

#sender: user1@qq.com
#psw: xxxx

sender: user3@qq.com
psw: xxx

subject: xxx项目WebUI自动化测试报告

#receiver: user1@qq.com,user2@qq.com
receiver:user3@qq.com
